Repository WildCodeSchool/tours-php-2009-project2-weshare, pull requests merged in 2020-11, with the labels that each got.

#3 Base projet
  src/View/base.html.twig
Labels: Correction done

#4 Force using composer 1 for the deployement
  Dockerfile
Labels: Waiting reviews

#8 Requests list
  db_weshare.sql
  public/assets/css/baseStyle.css
  public/assets/css/seeRequestStyleSheet.css
  public/assets/images/favicon.png
  public/assets/images/favicon_old.png
  public/assets/images/loupe_small_size.png
  public/assets/images/loupe_small_size2.png
  src/Controller/RequestController.php
  src/Model/AddressManager.php
  src/Model/MeasurementManager.php
  src/Model/RequestManager.php
  src/Model/TownManager.php
  src/View/Request/seeRequest.html.twig
  src/View/base.html.twig
Labels: Waiting reviews

#5 Registration form
  .gitignore
  db_weshare.sql
  public/assets/css/styleFormInscription.css
  src/Controller/RequestController.php
  src/Controller/UserController.php
  src/Model/TownManager.php
  src/Model/User.php
  src/Model/UserManager.php
  src/View/User/formInscription.html.twig
  src/View/base.html.twig
Labels: Correction done

#7 Demand form
  public/assets/css/style.css
  src/Controller/HomeController.php
  src/Controller/RequestController.php
  src/Model/Request.php
  src/Model/RequestManager.php
  src/View/Home/index.html.twig
  src/View/Request/requestForm.html.twig
  src/View/base.html.twig
Labels: Correction done

#12 Index style
  public/assets/css/indexStyle.css
  public/assets/css/seeRequestStyleSheet.css
  public/assets/css/styleFormInscription.css
  src/Model/User.php
  src/View/Home/index.html.twig
  src/View/User/formInscription.html.twig
  src/View/base.html.twig
Labels: reviewed

#10 Pr master
  README.md
  public/assets/css/baseStyle.css
  public/assets/css/indexStyle.css
  public/assets/css/seeRequestStyleSheet.css
  public/assets/css/styleFormInscription.css
  public/assets/js/burgerMenu.js
  src/Controller/RequestController.php
  src/Controller/UserController.php
  src/Model/AddressManager.php
  src/Model/MeasurementManager.php
  src/Model/RequestManager.php
  src/Model/TownManager.php
  src/Model/User.php
  src/Model/UserManager.php
  src/View/Home/index.html.twig
  src/View/Request/seeRequest.html.twig
  src/View/User/formInscription.html.twig
  src/View/base.html.twig
Labels: reviewed

#14 PR_master
  .gitignore
  README.md
  composer.json
  composer.lock
  config/config.php
  db_weshare.sql
  grumphp.yml
  public/assets/css/baseStyle.css
  public/assets/css/indexStyle.css
  public/assets/css/seeRequestStyleSheet.css
  public/assets/css/style.css
  public/assets/css/styleFormInscription.css
  public/assets/images/favicon.png
  public/assets/images/favicon_old.png
  public/assets/images/logo.png
  public/assets/images/logo1.png
  public/assets/images/loupe_small_size.png
  public/assets/images/loupe_small_size2.png
  public/assets/js/burgerMenu.js
  public/index.php
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Controller/RequestController.php
  src/Controller/UserController.php
  src/Model/AbstractManager.php
  src/Model/AddressManager.php
  src/Model/Connection.php
  src/Model/ItemManager.php
  src/Model/MeasurementManager.php
  src/Model/Request.php
  src/Model/RequestManager.php
  src/Model/TownManager.php
  src/Model/User.php
  src/Model/UserManager.php
  src/View/Home/index.html.twig
  src/View/Request/requestForm.html.twig
  src/View/Request/seeRequest.html.twig
  src/View/User/formInscription.html.twig
  src/View/base.html.twig
  src/View/layout.html.twig
  src/routing.php
Labels: reviewed

#13 Answered requests list
  src/Controller/RequestController.php
  src/Model/RequestManager.php
  src/View/Request/answeredRequests.html.twig
Labels: reviewed

#15 Themes
  public/assets/css/baseStyle.css
  public/assets/css/seeRequestStyleSheet.css
  public/assets/css/styleFormInscription.css
  public/assets/css/styleRequestForm.css
  public/assets/images/dark-theme-logo.png
  public/assets/images/unicorn-theme-logo.png
  src/View/base.html.twig
Labels: reviewed

#16 Footer
  composer.lock
  public/assets/css/baseStyle.css
  public/assets/images/013-twitter-1.png
  public/assets/images/034-instagram.png
  public/assets/images/039-github.png
  public/assets/images/045-facebook.png
  public/assets/images/fleche.png
  public/assets/js/returnTop.js
  src/View/base.html.twig
Labels: reviewed

#18 Base style
  public/assets/css/baseStyle.css
  public/assets/css/partnersStyle.css
  public/assets/css/presentationStyle.css
  public/assets/images/celia.png
  public/assets/images/emre.png
  public/assets/images/kevin.JPG
  public/assets/images/leo.jpg
  public/assets/images/presentation-desktop.png
  public/assets/images/quentin.png
  src/Controller/OthersController.php
  src/View/Others/legalMention.html.twig
  src/View/Others/partners.html.twig
  src/View/Others/presentationTeam.html.twig
  src/View/base.html.twig
Labels: reviewed

#17 Listexpress
  public/assets/css/baseStyle.css
  public/assets/css/cardsStyle.css
  public/assets/css/formStyle.css
  public/assets/css/indexStyle.css
  public/assets/css/listexpress.css
  public/assets/css/overlayStyle.css
  public/assets/css/seeRequestStyleSheet.css
  public/assets/css/styleFormInscription.css
  public/assets/css/styleRequestForm.css
  public/assets/js/burgerMenu.js
  public/assets/js/themes.js
  src/Controller/HomeController.php
  src/Controller/RequestController.php
  src/Model/RequestManager.php
  src/Model/UserManager.php
  src/View/Home/index.html.twig
  src/View/Request/answeredRequests.html.twig
  src/View/Request/listExpress.html.twig
  src/View/Request/requestForm.html.twig
  src/View/Request/seeRequest.html.twig
  src/View/User/formInscription.html.twig
  src/View/base.html.twig
Labels: reviewed

#20 Correction bugs
  src/Controller/RequestController.php
Labels: reviewed

#19 Add a delete button in acceptedList for deleting the requests after y…
  src/Controller/RequestController.php
  src/Model/RequestManager.php
  src/View/Request/answeredRequests.html.twig
Labels: reviewed

#24 delete medias, sizing the footer and added redirections
  public/assets/css/baseStyle.css
  src/View/base.html.twig
Labels: reviewed

#33 Design
  public/assets/css/indexStyle.css
  public/assets/images/hands.jpg
  public/assets/images/roundhands.png
  src/View/Home/index.html.twig
  src/View/Others/legalMention.html.twig
  src/View/base.html.twig
Labels: reviewed

#42 modif scroll to top arrow
  public/assets/css/baseStyle.css
  public/assets/images/fleche.png
  src/View/base.html.twig
Labels: reviewed

#44 Css
  public/assets/css/baseStyle.css
  public/assets/css/listexpress.css
  public/assets/css/partnersStyle.css
  public/assets/css/seeRequestStyleSheet.css
  public/assets/images/books.jpg
  public/assets/images/castle.png
  public/assets/images/quizz.png
  public/assets/images/wcs.png
  src/View/Home/index.html.twig
  src/View/Others/partners.html.twig
  src/View/Request/answeredRequests.html.twig
  src/View/Request/listExpress.html.twig
  src/View/User/formInscription.html.twig
Labels: reviewed

#43 Bugs
  public/assets/css/baseStyle.css
  public/assets/css/overlayStyle.css
  src/Controller/RequestController.php
  src/Model/Request.php
  src/Model/User.php
  src/View/Home/index.html.twig
  src/View/User/formInscription.html.twig
  src/routing.php
Labels: reviewed

#46 Design
  public/assets/images/presentation-desktop.png
Labels: reviewed

#45 Visual
  public/assets/css/baseStyle.css
  public/assets/css/indexStyle.css
  public/assets/css/overlayStyle.css
  public/assets/css/presentationStyle.css
  public/assets/css/seeRequestStyleSheet.css
  public/assets/images/dark-theme-logo.png
  src/View/Request/answeredRequests.html.twig
Labels: reviewed

#48 Footer css
  public/assets/css/baseStyle.css
  public/assets/css/partnersStyle.css
  public/assets/css/presentationStyle.css
  public/assets/images/013-twitter-1.png
  public/assets/images/034-instagram.png
  public/assets/images/045-facebook.png
  public/assets/images/favicon_old.png
  public/assets/images/github.png
  public/assets/images/hands.jpg
  public/assets/images/logo.png
  public/assets/images/loupe_small_size.png
  public/assets/images/roundhands.png
  src/View/Others/presentationTeam.html.twig
  src/View/base.html.twig
Labels: reviewed

#47 final css for me!
  public/assets/css/baseStyle.css
  public/assets/css/formStyle.css
  public/assets/css/indexStyle.css
  public/assets/css/overlayStyle.css
  public/assets/css/seeRequestStyleSheet.css
Labels: reviewed

#49 Visual
  public/assets/css/baseStyle.css
  src/View/Others/partners.html.twig
Labels: reviewed

#50 Final version for this sprint
  public/assets/css/baseStyle.css
  public/assets/css/formStyle.css
  public/assets/css/indexStyle.css
  public/assets/css/listexpress.css
  public/assets/css/overlayStyle.css
  public/assets/css/partnersStyle.css
  public/assets/css/presentationStyle.css
  public/assets/css/seeRequestStyleSheet.css
  public/assets/images/013-twitter-1.png
  public/assets/images/034-instagram.png
  public/assets/images/045-facebook.png
  public/assets/images/books.jpg
  public/assets/images/castle.png
  public/assets/images/dark-theme-logo.png
  public/assets/images/favicon_old.png
  public/assets/images/fleche.png
  public/assets/images/github.png
  public/assets/images/logo.png
  public/assets/images/loupe_small_size.png
  public/assets/images/presentation-desktop.png
  public/assets/images/quizz.png
  public/assets/images/wcs.png
  src/Controller/RequestController.php
  src/Model/Request.php
  src/Model/User.php
  src/View/Home/index.html.twig
  src/View/Others/legalMention.html.twig
  src/View/Others/partners.html.twig
  src/View/Others/presentationTeam.html.twig
  src/View/Request/answeredRequests.html.twig
  src/View/Request/listExpress.html.twig
  src/View/User/formInscription.html.twig
  src/View/base.html.twig
  src/routing.php
Labels: reviewed
